### PR TITLE
Add support for Channel 9 videos

### PR DESCRIPTION
**Pull request by san650**
Addresses #9

### CODE REVIEW

**Comment by WardCunningham** [comment]
Let us know if you want to try #14 as an alternative to this.

**Comment by san650** [comment]
I would merge this PR. I would like to work on #14 but it's going to take some time.

**Comment by paul90** [comment]
Thank you @san650 

Published as + wiki-plugin-video@0.2.4

**Comment by WardCunningham** [comment]
@san650 With Channel 9 now supported, we might want to add its most common url forms to the drop decoding for video. This is in the lib/drop package in wiki-client:
https://github.com/fedwiki/wiki-client/blob/master/lib/drop.coffee#L24-L43

We want to recognize pages that host the videos, not any old page that embeds it. This was not all that clear to me when I (vainly) searched for a few from the days I worked at Microsoft.
https://www.google.com/search?q=channel+9+msdn+ward+cunningham

We could discuss the options here or on a subsequent pull request.

Thanks again for your help.

**Pull request merged**
