### PR TITLE
Add tests

### LINKED ISSUE #13: Create a basic test suite
This plugin doesn't have a test suite.

### PR DESCRIPTION
**Pull request by san650**
Fixes #13

### CODE REVIEW

**Comment by WardCunningham** [comment]
Thank you for this contribution.

**Comment by WardCunningham** [comment]
As I look at this more I think that a better approach would be to test `parse` and `embed` separately. The emit just concatenates the results with some additional (reliable) escaping that need not be tested. The intermediate result between these two methods is easy to test for `parse` and easy to construct for `embed`. This saves having to worry about mocking $item or wiki.

**Comment by san650** [comment]
Ok, sounds reasonable. I'll change the tests to test each method separately.

**Comment by WardCunningham** [comment]
Thank you for your patience.

**Comment by san650** [comment]
@WardCunningham I've updated the PR

**Comment by WardCunningham** [comment]
Many thanks.

**Pull request merged**
